databaseChangeLog:
  - changeSet:
      id: 001-create-staging-schema
      author: walter claudio
      changes:
        - sql:
            sql: CREATE SCHEMA IF NOT EXISTS staging;

  - changeSet:
      id: 002-create-warehouse-schema
      author: walter claudio
      changes:
        - sql:
            sql: CREATE SCHEMA IF NOT EXISTS warehouse;
