databaseChangeLog:
  - include:
      file: 001-create-schemas.yaml
      relativeToChangelogFile: true
  - include:
      file: 002-create-tables.yaml
      relativeToChangelogFile: true
  - include:
      file: 003-add-event-version.yaml
      relativeToChangelogFile: true
