changeLogFile=changelog/db.changelog-master.yaml
url=jdbc:postgresql://postgres:5432/ride_hailing_dw
username=postgres
password=postgres
driver=org.postgresql.Driver
classpath=/liquibase/lib/postgresql.jar
